<?php
/**
 * Created by PhpStorm.
 * User: VitProg
 * Date: 10.09.15
 * Time: 15:11
 */

namespace vitprog\wamp;


use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\AssetBundle;

class Asset extends AssetBundle {

    public $sourcePath = '@vitprog/wamp/assets';

    public $js = [
        'wamp.js'
    ];

    public $depends = [
        'yii\web\JqueryAsset',
        'vitprog\wamp\WampyAsset',
    ];

    public static $jsSettings = [];

    public static function register($view, $jsSettings = []) {
        if (empty($jsSettings) === false) {
            static::$jsSettings = $jsSettings;
        }
        return parent::register($view); // TODO: Change the autogenerated stub
    }


    public function publish($am) {
        parent::publish($am);

        $jsSettings = ArrayHelper::merge([], static::$jsSettings);

        if ($jsSettings['uid']) {
            $jsSettings['uid'] = 'user' . $jsSettings['uid'];
        }

        $jsSettings = Json::encode($jsSettings);

        \Yii::$app->getView()->registerJs(<<<JS
    wamp.init({$jsSettings});
JS
        );
    }


}