#!/usr/bin/env php
<?php

require_once(__DIR__ . '/vendor/autoload.php');
require_once(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
require_once 'Daemon.php';

$config = \yii\helpers\ArrayHelper::merge(
    include ('config.php'),
    include ('config-local.php')
);

$daemon = new \vitprog\wamp\Daemon($config);
$daemon->run();